/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : Time,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'clientName' : string,
  'year' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'quote' : string,
  'company' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], bigint>,
  'createPortfolioItem' : ActorMethod<[PortfolioItem], bigint>,
  'createTestimonial' : ActorMethod<[Testimonial], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteContactMessage' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessage' : ActorMethod<[bigint], ContactMessage>,
  'getPortfolioItem' : ActorMethod<[bigint], PortfolioItem>,
  'getPortfolioItemsByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'getTestimonial' : ActorMethod<[bigint], Testimonial>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], bigint>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updatePortfolioItem' : ActorMethod<[PortfolioItem], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];