/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'clientName' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [IDL.Nat], []),
  'createPortfolioItem' : IDL.Func([PortfolioItem], [IDL.Nat], []),
  'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [PortfolioItem], ['query']),
  'getPortfolioItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getTestimonial' : IDL.Func([IDL.Nat], [Testimonial], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updatePortfolioItem' : IDL.Func([PortfolioItem], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'clientName' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [IDL.Nat], []),
    'createPortfolioItem' : IDL.Func([PortfolioItem], [IDL.Nat], []),
    'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
    'getPortfolioItem' : IDL.Func([IDL.Nat], [PortfolioItem], ['query']),
    'getPortfolioItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getTestimonial' : IDL.Func([IDL.Nat], [Testimonial], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [IDL.Nat], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updatePortfolioItem' : IDL.Func([PortfolioItem], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };